//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeroBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotCred {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotCred() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeroBot.BotCred", typeof(BotCred).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pf9l6u76hz2oxxkxqajj45sp80x76o.
        /// </summary>
        public static string BotAccToken {
            get {
                return ResourceManager.GetString("BotAccToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oauth:okn0ecb6vt28wmybsh4jibyydlxg7l.
        /// </summary>
        public static string BotAuth {
            get {
                return ResourceManager.GetString("BotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerobottwitch.
        /// </summary>
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9v9o1optvsrojpb26pgcl0rllyh24e.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dezerogue.
        /// </summary>
        public static string DefaultChannel {
            get {
                return ResourceManager.GetString("DefaultChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/2cVUXT2eYg.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODQ2ODI3NjcxNzA2MTQwNjk1.YK1Lug.RhDMVUV0fYQtobhXdzENPwhS4b4.
        /// </summary>
        public static string DiscordBotToken {
            get {
                return ResourceManager.GetString("DiscordBotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.com/api/webhooks/846892589323780116/BxaZIgu6q3hwYzoxPALS5JuFRZAnW639i7YwRLyai7xiQW46l-0Uv8y0-6bMET2rLkuh.
        /// </summary>
        public static string DiscordWebHook {
            get {
                return ResourceManager.GetString("DiscordWebHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyCgUu9f1YeY5Zsa1VVJePokpLj5kyuU6v8.
        /// </summary>
        public static string GoogleAPIKey {
            get {
                return ResourceManager.GetString("GoogleAPIKey", resourceCulture);
            }
        }
    }
}
